import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { loadConfig } from '../../../node_modules/mc-dev-harness/dist/core/config.js';
import { OwnedServer } from '../../../node_modules/mc-dev-harness/dist/adapters/runtime/server.js';
import { normalize } from '../../core/src/normalize.ts';
import { readSnapshot } from '../../core/src/snapshot.ts';
import { buildDatabase } from '../../core/src/db.ts';
import { audit } from '../../core/src/audit.ts';
import { diff } from '../../core/src/diff.ts';
import { bytesHash, hash } from '../../core/src/hash.ts';
import { evaluate } from './evaluate.ts';
import { runArtifacts, saveResults, waitFor, RequiredUnsupported } from './common.ts';
import { verifyCommonFixture } from './fabric-common.ts';
import type { Case } from './common.ts';
import type { Expectations } from '../../core/src/types.ts';
const root = resolve(fileURLToPath(new URL('../../../', import.meta.url))), session = resolve(process.argv[2]), runRoot = resolve(process.argv[3]), target = process.argv[4];
const negative = process.argv.includes('--negative'), cases: Case[] = [], ids = negative ? ['atlas.expected-failure'] : ['atlas.snapshot', 'atlas.reload', 'atlas.failure-fixture', 'atlas.stopped'];
const loaded = await loadConfig(root), artifacts = runArtifacts(runRoot, target);
const version = loaded.config.targets[target].loaderVersion!;
const runtime = { kind: 'server' as const, capabilities: ['dedicated-server'], setup: { executable: '{java:game}', args: ['-jar', '{tool:neoforge-server-1.21.1}', '--installServer', '.'] }, command: { executable: '{java:game}', args: ['-Xmx2G', '-Dcraftatlas.testWriteDelayMillis=2000', `@libraries/net/neoforged/neoforge/${version}/{os}_args.txt`, 'nogui'] }, readyPattern: 'Done \\(.*\\)! For help' };
const server = new OwnedServer(loaded, target, runtime, join(session, 'game'), join(session, 'game-logs'));
const controller = new AbortController();
process.once('SIGTERM', () => controller.abort()); process.once('SIGINT', () => controller.abort());
let stage = ids[0], finished = false;
try {
  process.stderr.write('Atlas: preparing recorded distribution and fixed pack\n');
  await server.prepare(artifacts, runRoot, controller.signal);
  mkdirSync(join(server.directory, 'world/datapacks'), { recursive: true });
  cpSync(join(root, 'fixtures/datapack'), join(server.directory, 'world/datapacks/atlas'), { recursive: true });
  cpSync(join(root, 'fixtures/scripts'), join(server.directory, 'scripts'), { recursive: true });
  await server.start(controller.signal); await server.waitReady();
  const capture = async (label: string) => {
    const mark = server.mark(); server.command(`craftatlas dump ${label}`);
    await server.waitForOutput(new RegExp(`CRAFTATLAS COMPLETE label=${label}`), 120000, mark);
    const path = join(server.directory, 'craftatlas', label);
    await waitFor('Fresh snapshot completion', () => existsSync(join(path, 'completion.json')), Boolean);
    const snapshot = readSnapshot(path);
    if (snapshot.completion.status !== 'complete') throw new RequiredUnsupported('Required raw collection is partial: ' + snapshot.completion.errors.join('; '));
    return snapshot;
  };
  const baseline = await capture('baseline'), model = normalize(baseline);
  const expectations = JSON.parse(readFileSync(join(root, 'fixtures/expectations.json'), 'utf8')) as Expectations;
  assert.ok(baseline.recipes.length > 100); assert.equal(baseline.mode, 'dedicated');
  assert.ok(baseline.recipes.some(r => r.id === 'crafttweaker:atlas_script'));
  assert.ok(!baseline.recipes.some(r => r.id === 'minecraft:gold_nugget'));
  assert.ok(model.processes.some(p => p.type === 'mekanism:enriching' && p.interpretation === 'supported' && p.unknown.length === 0 && p.inputs.every(i => i.alternatives.every(a => a.resource || a.tag))));
  assert.deepEqual(audit(model, expectations).filter(d => d.severity === 'error'), []);
  writeFileSync(join(session, 'common-fixture.json'), JSON.stringify(verifyCommonFixture(baseline, root), null, 2));
  if (negative) {
    const expected = JSON.parse(readFileSync(join(root, 'fixtures/negative-expectations.json'), 'utf8'));
    const diagnostics = audit(model, expected); writeFileSync(join(session, 'diagnostics.json'), JSON.stringify(diagnostics, null, 2));
    cases.push({ ...evaluate(model, expected), id: stage, message: 'Deliberate missing recipe/tag fixture; diagnostics.json' });
  } else {
    const repeat = normalize(await capture('repeat')); assert.equal(model.contentHash, repeat.contentHash);
    buildDatabase(join(session, 'baseline.sqlite'), model);
    cases.push({ id: stage, status: 'passed', message: `Runtime recipes=${baseline.recipes.length}; semantic hash ${model.contentHash}` });
    stage = 'atlas.reload';
    writeFileSync(join(server.directory, 'scripts/atlas.zs'), readFileSync(join(root, 'fixtures/scripts/atlas.zs'), 'utf8') + '\ncraftingTable.removeByName("atlas:added");\n');
    writeFileSync(join(server.directory, 'world/datapacks/atlas/data/minecraft/recipe/stick.json'), JSON.stringify({ type: 'minecraft:crafting_shapeless', ingredients: [{ item: 'minecraft:cobblestone' }], result: { id: 'minecraft:stick', count: 5 } }));
    writeFileSync(join(server.directory, 'world/datapacks/atlas/data/atlas/tags/item/alternatives.json'), '{"replace":true,"values":["minecraft:dirt"]}');
    const mark = server.mark(); server.command('craftatlas dump interrupted');
    await server.waitForOutput(/CRAFTATLAS CAPTURED label=interrupted/, 120000, mark);
    server.command('reload');
    await server.waitForOutput(/CRAFTATLAS RELOADING/, 120000, mark);
    await server.waitForOutput(/CRAFTATLAS RELOADED/, 120000, mark);
    await server.waitForOutput(/CRAFTATLAS FAILED label=interrupted/, 120000, mark);
    assert.equal(existsSync(join(server.directory, 'craftatlas/interrupted/completion.json')), false);
    const changed = await capture('changed'); assert.equal(changed.session, baseline.session); assert.ok(changed.generation > baseline.generation);
    assert.ok(!changed.recipes.some(r => r.id === 'atlas:added')); assert.deepEqual(changed.tags['atlas:alternatives'], ['minecraft:dirt']);
    const after = normalize(changed), differences = diff(model, after);
    assert.notEqual(model.contentHash, after.contentHash); assert.ok(differences.changes.length >= 3);
    writeFileSync(join(session, 'diff.json'), JSON.stringify(differences, null, 2)); buildDatabase(join(session, 'changed.sqlite'), after);
    cases.push({ id: stage, status: 'passed', message: `Reload generation ${changed.generation}; diff.json` });
    stage = 'atlas.failure-fixture';
    const diagnostics = audit(after, expectations); assert.ok(diagnostics.some(d => d.severity === 'error' && d.target === 'atlas:added'));
    writeFileSync(join(session, 'diagnostics.json'), JSON.stringify(diagnostics, null, 2));
    cases.push({ id: stage, status: 'passed', message: 'Actual removed required recipe detected as failed expectation; diagnostics.json' });
  }
  finished = true;
} catch (error) { process.stderr.write(String(error) + '\n'); cases.push({ id: stage, status: error instanceof RequiredUnsupported ? 'unsupported' : error instanceof assert.AssertionError ? 'failed' : 'infrastructure-error', message: String(error) }); }
finally {
  const stopped = await server.stop();
  if (!negative) cases.push({ id: 'atlas.stopped', status: stopped?.exitCode === 0 ? 'passed' : 'infrastructure-error', message: `Game exit ${stopped?.exitCode}` });
  for (const id of ids) if (!cases.some(c => c.id === id)) cases.push({ id, status: 'skipped', message: 'Prerequisite case did not complete' });
  const evidence = await server.collectEvidence();
  writeFileSync(join(session, 'evidence.json'), JSON.stringify({ schemaVersion: 1, runId: runRoot.split(/[\\/]/).at(-1), target, artifacts, packLockHash: bytesHash(readFileSync(join(root, 'fixtures/pack.lock.json'))), inputs: ['fixtures/expectations.json', 'fixtures/negative-expectations.json', 'fixtures/scripts/atlas.zs'].map(path => ({ path, sha256: bytesHash(readFileSync(join(root, path))) })), evidence: evidence.map(path => relative(runRoot, join(server.directory, path))), casesHash: hash(cases), finished }, null, 2));
  saveResults(session, cases);
}
