import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { join, resolve, delimiter } from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import { bytesHash, hash } from '../packages/core/src/hash.ts';
const root = resolve(fileURLToPath(new URL('../', import.meta.url))), args = process.argv.slice(2);
const option = (name: string) => args[args.indexOf(name) + 1];
if (!args.includes('--gson')) throw new Error('Use --gson <resolved-gson.jar> [--ecj <compiler.jar>] [--release 17|21]');
const gson = resolve(option('--gson')), release = args.includes('--release') ? option('--release') : '17';
assert.ok(['17','21'].includes(release));
mkdirSync(join(root, '.harness'), {recursive:true});
const temporary = mkdtempSync(join(root, '.harness/identity-probe-'));
const sources = ['JsonFiles.java','RuntimeIdentity.java'].map(name=>join(root,'mods/collector/src/main/java/dev/craftatlas',name));
sources.push(join(root,'mods/collector/src/test/identity/IdentityProbe.java'));
const flags = ['-encoding','UTF-8','-classpath',gson,'-d',temporary,...sources];
if (args.includes('--ecj')) execFileSync('java',['-jar',resolve(option('--ecj')),'-'+release,...flags],{stdio:'pipe'});
else execFileSync('javac',['--release',release,...flags],{stdio:'pipe'});
const result = execFileSync('java',['-classpath',[temporary,gson].join(delimiter),'dev.craftatlas.IdentityProbe',join(temporary,'game')],{encoding:'utf8'}).trim().split(/\r?\n/).map(line=>JSON.parse(line));
assert.equal(result.length,11); assert.equal(result[0].status,'unsupported');
assert.equal(result[1].status,'complete'); assert.equal(result[1].inputs['mods/mod.jar'],bytesHash('loaded-distribution'));
assert.equal(result[1].startupJarsHash,hash(result[1].loadedJars));assert.equal(result[1].startupInputsHash,hash(result[1].inputs));
assert.notEqual(result[1].inputs['config/mod.json'],result[2].inputs['config/mod.json']);
assert.notEqual(result[1].inputs['world/datapacks/pack/pack.mcmeta'],result[2].inputs['world/datapacks/pack/pack.mcmeta']);
assert.equal(result[2].generation,2); assert.equal(result[2].status,'unsupported');
assert.equal(result[3].launchNonce,result[1].launchNonce,'nonce is measured at boot, never relabeled from current files');
assert.notEqual(result[4].launchNonce,result[1].launchNonce); assert.notEqual(result[4].session,result[1].session);
for (const index of [5,6,7]) assert.equal(result[index].status,'unsupported');
assert.equal(result[8].status,'unsupported'); assert.equal(result[8].generation,2);
assert.equal(result[8].inputs['world/datapacks/pack/pack.mcmeta'],bytesHash('reloaded-pack'));
assert.equal(result[10].status,'complete');assert.equal(result[10].generation,2);assert.equal(result[10].startupInputsHash,hash(result[10].inputs));
assert.equal(result[9].status,'unsupported'); assert.notEqual(result[9].startupPropertiesHash,hash(result[9].jvmProperties));
process.stdout.write(JSON.stringify({schemaVersion:1,release,status:'passed',cases:11,boundary:'Pure Java runtime measurement; no Minecraft APIs or games loaded'})+'\n');
