import { mkdirSync, writeFileSync } from 'node:fs';
const str = { type: 'string', minLength: 1 }, strings = { type: 'array', items: str }, count = { type: 'number', minimum: 0 }, positive = { type: 'number', exclusiveMinimum: 0 };
const obj = <T extends object>(properties: T, required = Object.keys(properties)) => ({ type: 'object', additionalProperties: false, properties, required });
const list = (items: object) => ({ type: 'array', items });
const evidence = strings;
const alternative = obj({ resource: str, tag: str, members: strings, predicate: {}, components: {} }, []);
const slot = obj({ alternatives: list(alternative), amount: positive, unit: str, consumption: { enum: ['consumed', 'catalyst', 'durability'] }, evidence });
const output = obj({ resource: str, amount: positive, unit: str, role: { enum: ['primary', 'byproduct', 'returned'] }, probability: { anyOf: [{ type: 'number', minimum: 0, maximum: 1 }, { type: 'null' }] }, evidence, components: {} }, ['resource', 'amount', 'unit', 'role', 'probability', 'evidence']);
const requirement = obj({ kind: { enum: ['equipment', 'stage', 'dimension', 'context', 'opaque'] }, id: str, evidence, predicate: {} }, ['kind', 'id', 'evidence']);
const resource = obj({ id: str, kind: str, name: str, evidence, components: {} }, ['id', 'kind', 'name', 'evidence']);
const coverage = obj({ dataset: str, type: str, status: { enum: ['complete', 'partial', 'unsupported', 'failed'] }, enumerated: { anyOf: [{ type: 'integer', minimum: 0 }, { type: 'null' }] }, interpreted: { anyOf: [{ type: 'integer', minimum: 0 }, { type: 'null' }] }, reasons: strings });
const process = obj({ id: str, sourceId: str, type: str, inputs: list(slot), outputs: list(output), requirements: list(requirement), evidence, interpretation: { enum: ['supported', 'opaque'] }, execution: { enum: ['executable', 'display', 'unconfirmed'] }, unknown: strings, enabled: { type: 'boolean' }, costs: list(obj({ kind: str, amount: { anyOf: [count, { type: 'null' }] }, unit: str, basis: str })), raw: {}, fieldEvidence: { type: 'object', additionalProperties: evidence }, conflicts: strings });
Object.assign(process.properties, { fieldHistory: { type: 'object', additionalProperties: list(obj({ value: {}, evidence })) } });
const diagnostic = obj({ id: str, rule: str, target: str, severity: { enum: ['info', 'warning', 'error'] }, status: { enum: ['confirmed', 'unknown'] }, scenario: { type: ['string', 'null'] }, message: str, evidence, path: strings, unknown: strings, snapshotId: str });
const mods = list(obj({ id: str, version: str })), tags = { type: 'object', additionalProperties: strings };
const snapshot = obj({ schemaVersion: { const: 1 }, id: str, session: str, generation: { type: 'integer', minimum: 0 }, mode: { enum: ['dedicated', 'integrated'] }, minecraft: str, loader: str, loaderVersion: str, collectorVersion: str, mods, environment: {}, resources: list(resource), tags, recipes: list(obj({ id: str, type: str, data: {}, error: str }, ['id', 'type', 'data'])), coverage: list(coverage), completion: obj({ status: { enum: ['complete', 'partial', 'failed'] }, errors: strings }), viewer: obj({ session: str, generation: { type: 'integer', minimum: 0 }, context: {}, recipes: list(obj({ id: str, recipeId: { type: ['string', 'null'] }, category: str, inputs: list(slot), outputs: list(output), equipment: strings, execution: { enum: ['display', 'unconfirmed'] }, unknown: strings, raw: {} })), coverage: list(coverage) }) }, ['schemaVersion', 'id', 'session', 'generation', 'mode', 'minecraft', 'loader', 'loaderVersion', 'collectorVersion', 'mods', 'environment', 'resources', 'tags', 'recipes', 'coverage', 'completion']);
Object.assign(process.properties, { viewerSources: snapshot.properties.viewer.properties.recipes });
Object.assign(process.properties, { constraints: {} });
Object.assign(snapshot.properties.viewer.properties, { kind: { enum: ['jei', 'emi', 'rei'] }, version: str });
const rawRecord = obj({ id: str, type: str, data: {}, error: str }, ['id', 'type', 'data']);
Object.assign(snapshot.properties, { world: obj({ lootTables: list(rawRecord), lootModifiers: list(rawRecord), lootSources: list(rawRecord), biomes: list(rawRecord), dimensions: list(rawRecord), features: list(rawRecord), observations: list({}), limitations: strings }, ['lootTables', 'lootModifiers', 'lootSources', 'biomes', 'dimensions', 'features', 'limitations']) });
const boundedAmount = { type: 'number', exclusiveMinimum: 0, maximum: 1e12 };
const costRequest = obj({ schemaVersion: { const: 1 }, id: str, target: obj({ resource: str, amount: boundedAmount, unit: str }), routes: { type: 'object', maxProperties: 1000, additionalProperties: obj({ process: str, output: { type: 'integer', minimum: 0, maximum: 10000 } }) }, selections: { type: 'object', maxProperties: 1000, additionalProperties: { type: 'object', maxProperties: 1000, additionalProperties: str } }, mode: { enum: ['deterministic', 'expectation'] }, probabilityModels: { type: 'object', maxProperties: 1000, additionalProperties: obj({ kind: { const: 'iid-bernoulli' }, independentOutputs: { type: 'boolean' } }) }, durability: { type: 'object', maxProperties: 1000, additionalProperties: obj({ remaining: { type: 'number', minimum: 0, maximum: 1e12 }, lifetime: boundedAmount }) } });
Object.assign(costRequest.properties, { inventoryUnits: { type: "object", maxProperties: 1000, additionalProperties: str } });
const schemas = {
  snapshot, process, coverage, diagnostic, 'cost-request': costRequest,
  model: obj({ schemaVersion: { const: 1 }, snapshotId: str, session: str, generation: { type: 'integer', minimum: 0 }, normalizerVersion: str, environment: {}, mods, resources: list(resource), tags, processes: list(process), evidence: list(obj({ id: str, kind: { enum: ['runtime', 'viewer', 'definition', 'inference', 'observation'] }, source: str, adapter: str, pointer: str })), coverage: list(coverage), diagnostics: list(diagnostic), contentHash: str }),
  scenario: obj({ schemaVersion: { const: 1 }, id: str, inventory: { type: 'object', additionalProperties: count }, equipment: strings, stages: strings, dimensions: strings, forbiddenProcesses: strings, allowedTypes: { anyOf: [strings, { type: 'null' }] }, supply: { enum: ['renewable', 'finite'] }, closed: { type: 'boolean' }, closedResources: strings, gameRules: {} }),
  expectations: obj({ schemaVersion: { const: 1 }, recipes: strings, nonemptyTags: strings, supportedTypes: strings, reachable: strings, unreachable: strings }),
  definitions: obj({ schemaVersion: { const: 1 }, id: str, version: str, priority: { type: 'integer' }, targets: obj({ minecraft: str, loader: str, mods: list(obj({ id: str, versions: strings })) }), verified: strings, operations: list(obj({ id: str, selector: obj({ id: str, type: str }, []), action: { enum: ['append', 'replace', 'disable'] }, patch: obj({ inputs: list(slot), outputs: list(output), requirements: list(requirement), costs: process.properties.costs, unknown: strings, execution: process.properties.execution, interpretation: process.properties.interpretation }, []), evidence: str, override: strings })), additions: list(process) }),
};
mkdirSync('schemas', { recursive: true });
for (const [name, schema] of Object.entries(schemas)) writeFileSync(`schemas/${name}.schema.json`, JSON.stringify({ $schema: 'http://json-schema.org/draft-07/schema#', $id: `https://craft-atlas.local/schemas/${name}`, ...schema }, null, 2) + '\n');
